# Generated by Django 3.0.5 on 2020-06-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_trademark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, null=True),
        ),
    ]
