# Generated by Django 3.0.5 on 2020-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='timeend',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
