# Generated by Django 3.0.5 on 2020-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_news_timeend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='oldprice',
            new_name='reduced_price',
        ),
        migrations.AddField(
            model_name='product',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
