# Generated by Django 3.0.5 on 2020-07-10 13:51

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200702_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_long',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
