# Generated by Django 3.0.5 on 2020-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Mở', 'Mở'), ('Khóa', 'Khóa')], default='Mới', max_length=10),
        ),
    ]
