# Generated by Django 2.2.7 on 2020-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
