# Generated by Django 2.2.7 on 2020-05-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('1', 'Mới'), ('2', 'Đã xem')], default=1, max_length=12)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True, max_length=300)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
