# Generated by Django 3.0.5 on 2020-07-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200710_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListAddress',
        ),
    ]
