# Generated by Django 3.0.5 on 2020-07-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_city_district_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='listaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='listaddress',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listaddress',
            name='ward',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.Ward'),
            preserve_default=False,
        ),
    ]
