# Generated by Django 3.0.5 on 2020-07-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200726_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
