# Generated by Django 3.0.5 on 2020-07-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListAddress',
        ),
    ]
