# Generated by Django 3.0.5 on 2020-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Nữ', 'Nữ'), ('Nam', 'Nam'), ('Chưa xác định', 'Chưa xác định')], max_length=20, null=True),
        ),
    ]
