# Generated by Django 3.0.5 on 2020-06-05 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200603_0042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_shopcart_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=5)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('Mới', 'Mới'), ('Đã xác nhận', 'Đã xác nhận'), ('Chuẩn bị giao', 'Chuẩn bị giao'), ('Đang vận chuyển', 'Đang vận chuyển'), ('Hoàn thành', 'Hoàn thành'), ('Hủy', 'Hủy')], default='Mới', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('status', models.CharField(choices=[('Mới', 'Mới'), ('Đã xác nhận', 'Đã xác nhận'), ('Đã hủy', 'Đã hủy')], default='Mới', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
