# Generated by Django 3.0.5 on 2020-07-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
