# Generated by Django 2.2.7 on 2020-07-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
    ]
